{% set name = "pydatamail_ml" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydatamail_ml-{{ version }}.tar.gz
  sha256: e927e8923a6c5471289af67109fbdb4315dda9dea8ff9b329d4177e73151acd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bleach >=5.0.1
    - cssutils >=2.5.0
    - langdetect >=1.0.9
    - numpy >=1.23.1
    - pandas >=1.4.3
    - python >=3.6
    - pydatamail >=0.0.9
    - scikit-learn >=1.1.1
    - sqlalchemy >=1.4.39
    - tqdm >=4.64.0

test:
  imports:
    - pydatamail_ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pydatamail_ml
  summary: pydatamail_ml - Machine Learning extension for pydatamail
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
